language: node_js
node_js: stable
dist: trusty
script:
- bash ./gpages_build.sh brendena "sound-rebound" brenden "cerebralasylum1@gmail.com"
sudo: required
addons:
  firefox: latest
  sauce_connect: true
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install -g bower polylint web-component-tester
- bower install
- export PATH=$PWD/node_modules/.bin:$PATH

script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --skip-plugin local; fi
env:
  global:
  - secure: x9c2ZiFWryN1q5ApWrygUBOQa3QLy2aZBvGEr6JzzCwiJiUqf+1LFO3RP/eYUO8BeOF+OHb7//Lb59UoiTPUr5M/Rp2/hLD22EimGk5CZeajug0NoyETWmaDr/7Tp9KfKgAY7q9w42yTs40jbSTjsSDUfOqe6S8+CZaMszBJWFTgaA4rrlThGlfsagLFriBY0+/J+zoV0Lwx6Vtw+PBaXSV5ZsfoNLJYrUCO065BpLXFqDFJI5eGkeXmEefRO+B+HPrvxotFYI1ng3k905aXPm+G1FsJnFnepde5cShwkirHWvxPlZawcW7wqQ5RdnseS2UrpZimkSrrk/91m8bQ/O6LxDA4zU5G2L9giAvTjh4Sd7D85JGZrtzicKNZx0/YAIjuCgnABESF4OVdhhsprJRha1r2BaJSH8+EUQAgPyg4mVQmWPIbyNuWuDJIeSIfJYkVLXlpxkDKAH1LiFdV4XwmBQoPQYo4ANwlXpsb3YxjHiiL96hmfrgmzefe7VZ2CjkGNt/77rWPDIGjmXpSGMYkxAWkeOUZrhCWg/WS8p0+/ib4GER/I5dXkPC8uZCV5B6MalGcL8VHmQQUUXe0HkxO6J45iXUJHgIfyJqX+ylTX5FPtIMaSodBTua6+yfmDpfYgNrNk6QTMR/CqUJwpNTcdPWohpwNoPqSTDnXVmY=
  - secure: NLaayXrCC/auytR6SyR2Fsw4MglP3CuPB9mE3tyfZEhFo0p43WFZZZYtYf/5cFAPzXR+VNyOV7byVC4arvWbdBHFYz0NURv7RkPU/1dTRzWODwwhd8OD+ig1VskLGjxBmVv7mOeLEPwnu+YHSiYWScIc1Kf1uutKZOPhptiSvNMuxDg+eL7W76rV9/vVOycF3FVfIvYixR0UXiAfjPR5p83GAyBXzC0tsRerVBLhHVOBHgqn1LpcbLlckxWZV5bYbpKMAKvf5kNXOwV9K+mdp++WAWW55ErKHGsKyaLtZUN5sT/RvqjXEUor0ndYINkhG4Oh/L6Dr3Nxk65ezJVBRh6kHPl6tTwGod0lzwrPl+EdzDB0xo6RoHwPnBSpZHeEjoij8T0ZvxBLV5hwBBCjmr1lKwPf9ppvYKqVJAUZ09vVU/oCKpeQtV/MFUP5y7Bui6vG4FhsmOcGm9FEX5wIdLyvdnHsaqUDrKL9XryrNlbTwRb5fB+EX3BxeqqvmG/xrJhYiK/g28iqlNH8TWTpAbAW2kosNBW/h5sFyijhofC9zTeFQ44cai40/VsSFWH+E8Z0WWytdsjzT5Sx0pu5RKPFWyMr+APKZBlfQ+n/KcksIEzyOpZWUh5mbRXJd+P9kxnSOkWOcvrIjp24qhz5BNvssyYFWwiJdoJmc0n11Bo=
